const apiKey: string = '421f9cebe38d426cb86184735231609'

export const baseURL: string = `https://api.weatherapi.com/v1/forecast.json?key=${apiKey}`




export const danni = {
    "location": {
        "name": "Tashkent",
        "region": "Toshkent",
        "country": "Uzbekistan",
        "lat": 41.32,
        "lon": 69.25,
        "tz_id": "Asia/Tashkent",
        "localtime_epoch": 1694905655,
        "localtime": "2023-09-17 4:07"
    },
    "current": {
        "last_updated_epoch": 1694905200,
        "last_updated": "2023-09-17 04:00",
        "temp_c": 18,
        "temp_f": 64.4,
        "is_day": 0,
        "condition": {
            "text": "Clear",
            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
            "code": 1000
        },
        "wind_mph": 6.9,
        "wind_kph": 11.2,
        "wind_degree": 100,
        "wind_dir": "E",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 52,
        "cloud": 0,
        "feelslike_c": 18,
        "feelslike_f": 64.4,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 1,
        "gust_mph": 1.3,
        "gust_kph": 2.2
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2023-09-17",
                "date_epoch": 1694908800,
                "day": {
                    "maxtemp_c": 30.2,
                    "maxtemp_f": 86.4,
                    "mintemp_c": 18.3,
                    "mintemp_f": 64.9,
                    "avgtemp_c": 23.9,
                    "avgtemp_f": 75,
                    "maxwind_mph": 6.3,
                    "maxwind_kph": 10.1,
                    "totalprecip_mm": 0,
                    "totalprecip_in": 0,
                    "totalsnow_cm": 0,
                    "avgvis_km": 10,
                    "avgvis_miles": 6,
                    "avghumidity": 22,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000
                    },
                    "uv": 6
                },
                "astro": {
                    "sunrise": "06:05 AM",
                    "sunset": "06:30 PM",
                    "moonrise": "08:04 AM",
                    "moonset": "07:31 PM",
                    "moon_phase": "Waxing Crescent",
                    "moon_illumination": "3",
                    "is_moon_up": 0,
                    "is_sun_up": 0
                },
                "hour": [
                    {
                        "time_epoch": 1694890800,
                        "time": "2023-09-17 00:00",
                        "temp_c": 20.9,
                        "temp_f": 69.6,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 17,
                        "wind_dir": "NNE",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 27,
                        "cloud": 4,
                        "feelslike_c": 20.9,
                        "feelslike_f": 69.6,
                        "windchill_c": 20.9,
                        "windchill_f": 69.6,
                        "heatindex_c": 20.9,
                        "heatindex_f": 69.6,
                        "dewpoint_c": 1.1,
                        "dewpoint_f": 34,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694894400,
                        "time": "2023-09-17 01:00",
                        "temp_c": 20.5,
                        "temp_f": 68.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 27,
                        "wind_dir": "NNE",
                        "pressure_mb": 1012,
                        "pressure_in": 29.88,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 27,
                        "cloud": 3,
                        "feelslike_c": 20.5,
                        "feelslike_f": 68.9,
                        "windchill_c": 20.5,
                        "windchill_f": 68.9,
                        "heatindex_c": 20.5,
                        "heatindex_f": 68.9,
                        "dewpoint_c": 0.9,
                        "dewpoint_f": 33.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694898000,
                        "time": "2023-09-17 02:00",
                        "temp_c": 20.2,
                        "temp_f": 68.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 36,
                        "wind_dir": "NE",
                        "pressure_mb": 1011,
                        "pressure_in": 29.86,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 27,
                        "cloud": 3,
                        "feelslike_c": 20.2,
                        "feelslike_f": 68.4,
                        "windchill_c": 20.2,
                        "windchill_f": 68.4,
                        "heatindex_c": 20.2,
                        "heatindex_f": 68.4,
                        "dewpoint_c": 0.5,
                        "dewpoint_f": 32.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 8.9,
                        "gust_kph": 14.4,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694901600,
                        "time": "2023-09-17 03:00",
                        "temp_c": 19.9,
                        "temp_f": 67.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 13,
                        "wind_dir": "NNE",
                        "pressure_mb": 1011,
                        "pressure_in": 29.87,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 27,
                        "cloud": 5,
                        "feelslike_c": 19.9,
                        "feelslike_f": 67.8,
                        "windchill_c": 19.9,
                        "windchill_f": 67.8,
                        "heatindex_c": 19.9,
                        "heatindex_f": 67.8,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694905200,
                        "time": "2023-09-17 04:00",
                        "temp_c": 18,
                        "temp_f": 64.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 100,
                        "wind_dir": "E",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 52,
                        "cloud": 0,
                        "feelslike_c": 19.5,
                        "feelslike_f": 67.1,
                        "windchill_c": 19.5,
                        "windchill_f": 67.1,
                        "heatindex_c": 19.5,
                        "heatindex_f": 67.1,
                        "dewpoint_c": 0.2,
                        "dewpoint_f": 32.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 1.3,
                        "gust_kph": 2.2,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694908800,
                        "time": "2023-09-17 05:00",
                        "temp_c": 19.1,
                        "temp_f": 66.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 0.9,
                        "wind_kph": 1.4,
                        "wind_degree": 166,
                        "wind_dir": "SSE",
                        "pressure_mb": 1012,
                        "pressure_in": 29.88,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 28,
                        "cloud": 3,
                        "feelslike_c": 19.1,
                        "feelslike_f": 66.4,
                        "windchill_c": 19.1,
                        "windchill_f": 66.4,
                        "heatindex_c": 19.1,
                        "heatindex_f": 66.4,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 1.8,
                        "gust_kph": 2.9,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694912400,
                        "time": "2023-09-17 06:00",
                        "temp_c": 18.4,
                        "temp_f": 65.1,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 168,
                        "wind_dir": "SSE",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 30,
                        "cloud": 8,
                        "feelslike_c": 18.4,
                        "feelslike_f": 65.1,
                        "windchill_c": 18.4,
                        "windchill_f": 65.1,
                        "heatindex_c": 18.4,
                        "heatindex_f": 65.1,
                        "dewpoint_c": 0.4,
                        "dewpoint_f": 32.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 7.6,
                        "gust_kph": 12.2,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694916000,
                        "time": "2023-09-17 07:00",
                        "temp_c": 18.3,
                        "temp_f": 64.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 172,
                        "wind_dir": "S",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 29,
                        "cloud": 11,
                        "feelslike_c": 18.3,
                        "feelslike_f": 64.9,
                        "windchill_c": 18.3,
                        "windchill_f": 64.9,
                        "heatindex_c": 18.3,
                        "heatindex_f": 64.9,
                        "dewpoint_c": 0.2,
                        "dewpoint_f": 32.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 9.2,
                        "gust_kph": 14.8,
                        "uv": 5
                    },
                    {
                        "time_epoch": 1694919600,
                        "time": "2023-09-17 08:00",
                        "temp_c": 20,
                        "temp_f": 68,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 175,
                        "wind_dir": "S",
                        "pressure_mb": 1013,
                        "pressure_in": 29.91,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 27,
                        "cloud": 6,
                        "feelslike_c": 20,
                        "feelslike_f": 68,
                        "windchill_c": 20,
                        "windchill_f": 68,
                        "heatindex_c": 20,
                        "heatindex_f": 68,
                        "dewpoint_c": 0.2,
                        "dewpoint_f": 32.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 7.4,
                        "gust_kph": 11.9,
                        "uv": 6
                    },
                    {
                        "time_epoch": 1694923200,
                        "time": "2023-09-17 09:00",
                        "temp_c": 22,
                        "temp_f": 71.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 184,
                        "wind_dir": "S",
                        "pressure_mb": 1013,
                        "pressure_in": 29.9,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 24,
                        "cloud": 11,
                        "feelslike_c": 22.6,
                        "feelslike_f": 72.7,
                        "windchill_c": 22,
                        "windchill_f": 71.6,
                        "heatindex_c": 22.6,
                        "heatindex_f": 72.7,
                        "dewpoint_c": 0.6,
                        "dewpoint_f": 33.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 6.7,
                        "gust_kph": 10.8,
                        "uv": 6
                    },
                    {
                        "time_epoch": 1694926800,
                        "time": "2023-09-17 10:00",
                        "temp_c": 24.1,
                        "temp_f": 75.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly cloudy",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 198,
                        "wind_dir": "SSW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.89,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 22,
                        "cloud": 30,
                        "feelslike_c": 23.4,
                        "feelslike_f": 74.1,
                        "windchill_c": 24.1,
                        "windchill_f": 75.4,
                        "heatindex_c": 23.4,
                        "heatindex_f": 74.1,
                        "dewpoint_c": 0.8,
                        "dewpoint_f": 33.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 6.3,
                        "gust_kph": 10.1,
                        "uv": 6
                    },
                    {
                        "time_epoch": 1694930400,
                        "time": "2023-09-17 11:00",
                        "temp_c": 25.9,
                        "temp_f": 78.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 229,
                        "wind_dir": "SW",
                        "pressure_mb": 1012,
                        "pressure_in": 29.88,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 20,
                        "cloud": 16,
                        "feelslike_c": 24.4,
                        "feelslike_f": 75.9,
                        "windchill_c": 25.9,
                        "windchill_f": 78.6,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 1,
                        "dewpoint_f": 33.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 5.4,
                        "gust_kph": 8.6,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694934000,
                        "time": "2023-09-17 12:00",
                        "temp_c": 27.6,
                        "temp_f": 81.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 257,
                        "wind_dir": "WSW",
                        "pressure_mb": 1011,
                        "pressure_in": 29.85,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 17,
                        "cloud": 12,
                        "feelslike_c": 25.7,
                        "feelslike_f": 78.3,
                        "windchill_c": 27.6,
                        "windchill_f": 81.7,
                        "heatindex_c": 25.7,
                        "heatindex_f": 78.3,
                        "dewpoint_c": 0.5,
                        "dewpoint_f": 32.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694937600,
                        "time": "2023-09-17 13:00",
                        "temp_c": 28.8,
                        "temp_f": 83.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4,
                        "wind_kph": 6.5,
                        "wind_degree": 276,
                        "wind_dir": "W",
                        "pressure_mb": 1010,
                        "pressure_in": 29.84,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 15,
                        "cloud": 9,
                        "feelslike_c": 26.7,
                        "feelslike_f": 80.1,
                        "windchill_c": 28.8,
                        "windchill_f": 83.8,
                        "heatindex_c": 26.7,
                        "heatindex_f": 80.1,
                        "dewpoint_c": -0.3,
                        "dewpoint_f": 31.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694941200,
                        "time": "2023-09-17 14:00",
                        "temp_c": 29.8,
                        "temp_f": 85.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4,
                        "wind_kph": 6.5,
                        "wind_degree": 293,
                        "wind_dir": "WNW",
                        "pressure_mb": 1010,
                        "pressure_in": 29.82,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 14,
                        "cloud": 3,
                        "feelslike_c": 27.6,
                        "feelslike_f": 81.7,
                        "windchill_c": 29.8,
                        "windchill_f": 85.6,
                        "heatindex_c": 27.6,
                        "heatindex_f": 81.7,
                        "dewpoint_c": -0.8,
                        "dewpoint_f": 30.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 4.7,
                        "gust_kph": 7.6,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694944800,
                        "time": "2023-09-17 15:00",
                        "temp_c": 30.2,
                        "temp_f": 86.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 305,
                        "wind_dir": "NW",
                        "pressure_mb": 1009,
                        "pressure_in": 29.8,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 13,
                        "cloud": 15,
                        "feelslike_c": 28,
                        "feelslike_f": 82.4,
                        "windchill_c": 30.2,
                        "windchill_f": 86.4,
                        "heatindex_c": 28,
                        "heatindex_f": 82.4,
                        "dewpoint_c": -1.2,
                        "dewpoint_f": 29.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 5.1,
                        "gust_kph": 8.3,
                        "uv": 8
                    },
                    {
                        "time_epoch": 1694948400,
                        "time": "2023-09-17 16:00",
                        "temp_c": 30.2,
                        "temp_f": 86.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.3,
                        "wind_kph": 6.8,
                        "wind_degree": 300,
                        "wind_dir": "WNW",
                        "pressure_mb": 1009,
                        "pressure_in": 29.8,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 13,
                        "cloud": 9,
                        "feelslike_c": 28,
                        "feelslike_f": 82.4,
                        "windchill_c": 30.2,
                        "windchill_f": 86.4,
                        "heatindex_c": 28,
                        "heatindex_f": 82.4,
                        "dewpoint_c": -1.2,
                        "dewpoint_f": 29.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 4.9,
                        "gust_kph": 7.9,
                        "uv": 8
                    },
                    {
                        "time_epoch": 1694952000,
                        "time": "2023-09-17 17:00",
                        "temp_c": 29.9,
                        "temp_f": 85.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 297,
                        "wind_dir": "WNW",
                        "pressure_mb": 1009,
                        "pressure_in": 29.8,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 13,
                        "cloud": 8,
                        "feelslike_c": 27.7,
                        "feelslike_f": 81.9,
                        "windchill_c": 29.9,
                        "windchill_f": 85.8,
                        "heatindex_c": 27.7,
                        "heatindex_f": 81.9,
                        "dewpoint_c": -1,
                        "dewpoint_f": 30.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 5.6,
                        "gust_kph": 9,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694955600,
                        "time": "2023-09-17 18:00",
                        "temp_c": 28.1,
                        "temp_f": 82.6,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 300,
                        "wind_dir": "WNW",
                        "pressure_mb": 1009,
                        "pressure_in": 29.8,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 15,
                        "cloud": 3,
                        "feelslike_c": 26.1,
                        "feelslike_f": 79,
                        "windchill_c": 28.1,
                        "windchill_f": 82.6,
                        "heatindex_c": 26.1,
                        "heatindex_f": 79,
                        "dewpoint_c": -0.6,
                        "dewpoint_f": 30.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 8.1,
                        "gust_kph": 13,
                        "uv": 7
                    },
                    {
                        "time_epoch": 1694959200,
                        "time": "2023-09-17 19:00",
                        "temp_c": 25.8,
                        "temp_f": 78.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6,
                        "wind_kph": 9.7,
                        "wind_degree": 307,
                        "wind_dir": "NW",
                        "pressure_mb": 1009,
                        "pressure_in": 29.81,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 19,
                        "cloud": 3,
                        "feelslike_c": 24.4,
                        "feelslike_f": 75.9,
                        "windchill_c": 25.9,
                        "windchill_f": 78.6,
                        "heatindex_c": 24.4,
                        "heatindex_f": 75.9,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 11.6,
                        "gust_kph": 18.7,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694962800,
                        "time": "2023-09-17 20:00",
                        "temp_c": 24.7,
                        "temp_f": 76.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 321,
                        "wind_dir": "NW",
                        "pressure_mb": 1010,
                        "pressure_in": 29.82,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 21,
                        "cloud": 3,
                        "feelslike_c": 23.7,
                        "feelslike_f": 74.7,
                        "windchill_c": 24.7,
                        "windchill_f": 76.5,
                        "heatindex_c": 23.7,
                        "heatindex_f": 74.7,
                        "dewpoint_c": 0.7,
                        "dewpoint_f": 33.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 11.9,
                        "gust_kph": 19.1,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694966400,
                        "time": "2023-09-17 21:00",
                        "temp_c": 23.9,
                        "temp_f": 75,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 343,
                        "wind_dir": "NNW",
                        "pressure_mb": 1010,
                        "pressure_in": 29.83,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 21,
                        "cloud": 3,
                        "feelslike_c": 23.2,
                        "feelslike_f": 73.8,
                        "windchill_c": 23.9,
                        "windchill_f": 75,
                        "heatindex_c": 23.2,
                        "heatindex_f": 73.8,
                        "dewpoint_c": 0.4,
                        "dewpoint_f": 32.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 9.8,
                        "gust_kph": 15.8,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694970000,
                        "time": "2023-09-17 22:00",
                        "temp_c": 23.2,
                        "temp_f": 73.8,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 3.8,
                        "wind_kph": 6.1,
                        "wind_degree": 7,
                        "wind_dir": "N",
                        "pressure_mb": 1010,
                        "pressure_in": 29.82,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 22,
                        "cloud": 3,
                        "feelslike_c": 22.9,
                        "feelslike_f": 73.2,
                        "windchill_c": 23.1,
                        "windchill_f": 73.6,
                        "heatindex_c": 22.9,
                        "heatindex_f": 73.2,
                        "dewpoint_c": 0.3,
                        "dewpoint_f": 32.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 7.4,
                        "gust_kph": 11.9,
                        "uv": 1
                    },
                    {
                        "time_epoch": 1694973600,
                        "time": "2023-09-17 23:00",
                        "temp_c": 22.5,
                        "temp_f": 72.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 43,
                        "wind_dir": "NE",
                        "pressure_mb": 1010,
                        "pressure_in": 29.82,
                        "precip_mm": 0,
                        "precip_in": 0,
                        "humidity": 23,
                        "cloud": 3,
                        "feelslike_c": 22.7,
                        "feelslike_f": 72.9,
                        "windchill_c": 22.5,
                        "windchill_f": 72.5,
                        "heatindex_c": 22.7,
                        "heatindex_f": 72.9,
                        "dewpoint_c": 0.4,
                        "dewpoint_f": 32.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10,
                        "vis_miles": 6,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 1
                    }
                ]
            }
        ]
    }
}